### ISSUE TITLE
UnboundLocalError: local variable 'c' referenced before assignment

### ISSUE THREAD

**Issue by w-simon** [ctuning/ck-env#77]
1, browse   http://cknowledge.org/repo/web.php?template=ck-ai-basic&action=index&module_uoa=wfe&native_action=show&native_module_uoa=advice

2, select  "use machine learning to predict compiler flags"

3, input Program source code like this:
/* Sample C kernel to demonstrate MILEPOST optimization prediction */

#include <stdio.h>

void test()
{
int i, j;

j = 0;
for(i = 0; i < 1000; i++)
    j +=i;
}

int main(void)
{
  int i,j;
  float x[100];

  for (j=0; j<16; j++)
   for (i=0; i<16; i++)
    x[i+j]=i*j*1.2;

  printf("x[5]=%f", x[5]);

  return 0;
}

4, then click "Extract features". We will find this error:

Traceback (most recent call last):
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 9611, in 
    r=access(sys.argv[1:])
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 9567, in access
    rr=perform_action(i)
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 3457, in perform_action
    return a(i)
  File "/home/fursin/CK/ck-web/module/wfe/module.py", line 417, in index
    rx=ck.access(ii)
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 9567, in access
    rr=perform_action(i)
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 3457, in perform_action
    return a(i)
  File "/home/fursin/CK/ck-analytics/module/advice/module.py", line 161, in show
    r=ck.access(ii)
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 9567, in access
    rr=perform_action(i)
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 3457, in perform_action
    return a(i)
  File "/home/fursin/CK/reproduce-milepost-project/module/milepost/module.py", line 623, in ask_ai_web
    return show(i)
  File "/home/fursin/CK/reproduce-milepost-project/module/milepost/module.py", line 270, in show
    'dict':dprog})
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 9567, in access
    rr=perform_action(i)
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 3457, in perform_action
    return a(i)
  File "/home/fursin/CK/ck-autotuning/module/program/module.py", line 7096, in add
    r=ck.access(i)
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 9567, in access
    rr=perform_action(i)
  File "/home/fursin/fggwork/ck/ck/kernel.py", line 3457, in perform_action
    return a(i)
  File "/home/fursin/CK/ck-env/module/misc/module.py", line 409, in prepare_entry_template
    tuoa=c['data_uid']
UnboundLocalError: local variable 'c' referenced before assignment

**Comment by gfursin** [comment]
Thanks @w-simon for reporting this bug. I believe I fixed it (actually in two places). Just one more thing - you have a syntax error in your above program - you should fix the line:

**Comment by gfursin** [comment]
```
x[i+j]=ij1.2;
```
to
```
x[i+j]=i/1.2;
```
I fixed CK modules and managed to extract features from this program:
```
#include <stdio.h>

void test()
{
int i, j;

j = 0;
for(i = 0; i < 1000; i++)
j +=i;
}

int main(void)
{
int i,j;
float x[100];

for (j=0; j<16; j++)
for (i=0; i<16; i++)
x[i+j]=i/1.2;

printf("x[5]=%f", x[5]);

return 0;
}
```
Thanks!
