### ISSUE TITLE
Bazel compile fails on x86 Ubuntu 18.04

### ISSUE THREAD

**Issue by ztyree42** [ctuning/ck-env#99]
Running ck install package:lib-tensorflow-1.10.1-src-cuda-xla inside the ctuning/ck-ubuntu-18.04 docker container fails on Bazel compile with:

> ** PATCH **
> ** COMPILE **
> Building Bazel from scratch......
> Building Bazel with Bazel.
> .WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/tmp/bazel_KjG9DrmJ/archive/libblaze.jar) to field java.nio.Buffer.address
> WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
> INFO: Analysed target //src:bazel (213 packages loaded).
> INFO: Found 1 target...
> INFO: From Compiling src/main/cpp/blaze_util_posix.cc:
> src/main/cpp/blaze_util_posix.cc: In function 'void blaze::Daemonize(const char*, bool)':
> src/main/cpp/blaze_util_posix.cc:217:3: warning: ignoring return value of 'int dup(int)', declared with attribute warn_unused_result [-Wunused-result]
>    (void) dup(STDOUT_FILENO);  // stderr (2>&1)
>    ^~~~~~~~~~~~~~~~~~~~~~~~~
> src/main/cpp/blaze_util_posix.cc: In function 'void blaze::DieAfterFork(const char*)':
> src/main/cpp/blaze_util_posix.cc:264:8: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
>    write(STDERR_FILENO, message, strlen(message));  // strlen should be OK
>    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/main/cpp/blaze_util_posix.cc:265:8: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
>    write(STDERR_FILENO, ": ", 2);
>    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
> src/main/cpp/blaze_util_posix.cc:266:8: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
>    write(STDERR_FILENO, error_string, strlen(error_string));
>    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/main/cpp/blaze_util_posix.cc:267:8: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
>    write(STDERR_FILENO, "\n", 1);
>    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
> src/main/cpp/blaze_util_posix.cc: In function 'uint64_t blaze::AcquireLock(const string&, bool, bool, blaze::BlazeLock*)':
> src/main/cpp/blaze_util_posix.cc:629:3: warning: ignoring return value of 'int ftruncate(int, __off_t)', declared with attribute warn_unused_result [-Wunused-result]
>    (void) ftruncate(lockfd, 0);
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> INFO: From JavacBootstrap src/main/java/com/google/devtools/build/lib/shell/libshell-skylark.jar [for host]:
> warning: [options] bootstrap class path not set in conjunction with -source 8
> warning: Implicitly compiled files were not subject to annotation processing.
>   Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
> 2 warnings
> INFO: From JavacBootstrap src/java_tools/singlejar/java/com/google/devtools/build/singlejar/libbootstrap.jar [for host]:
> warning: [options] bootstrap class path not set in conjunction with -source 8
> warning: Implicitly compiled files were not subject to annotation processing.
>   Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
> 2 warnings
> INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar [for host]:
> warning: [options] bootstrap class path not set in conjunction with -source 8
> warning: Implicitly compiled files were not subject to annotation processing.
>   Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 2 warnings
> INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/jarhelper/libbootstrap_jarhelper.jar [for host]:
> warning: [options] bootstrap class path not set in conjunction with -source 8
> 1 warning
> INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap_VanillaJavaBuilder.jar [for host]:
> warning: [options] bootstrap class path not set in conjunction with -source 8
> warning: Implicitly compiled files were not subject to annotation processing.
>   Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
> Note: src/java_tools/buildjar/java/com/google/devtools/build/buildjar/VanillaJavaBuilder.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 2 warnings
> INFO: From Generating Java (Immutable) proto_library @googleapis//:google_devtools_build_v1_build_events_proto:
> google/devtools/build/v1/build_events.proto: warning: Import google/rpc/status.proto but not used.
> INFO: From Generating Java (Immutable) proto_library @googleapis//:google_watch_v1_proto:
> google/watcher/v1/watch.proto: warning: Import google/protobuf/empty.proto but not used.
> INFO: From Generating Java (Immutable) proto_library @googleapis//:google_bytestream_bytestream_proto:
> google/bytestream/bytestream.proto: warning: Import google/protobuf/wrappers.proto but not used.
> INFO: From SkylarkAction external/googleapis/google_bytestream_bytestream_java_grpc_srcs.jar:
> google/bytestream/bytestream.proto: warning: Import google/protobuf/wrappers.proto but not used.
> INFO: From SkylarkAction external/googleapis/google_watch_v1_java_grpc_srcs.jar:
> google/watcher/v1/watch.proto: warning: Import google/protobuf/empty.proto but not used.
> ERROR: /CK-TOOLS/tool-bazel-0.15.2-linux-64/src/src/main/java/com/google/devtools/build/lib/BUILD:1336:1: Building src/main/java/com/google/devtools/build/lib/libbazel-class.jar () failed: Worker process returned an unparseable WorkResponse!
> 
> Did you try to print something to stdout? Workers aren't allowed to do this, as it breaks the protocol between Bazel and the worker process.
> 
> ---8<---8<--- Exception details ---8<---8<---
> com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
> 	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
> 	at com.google.protobuf.CodedInputStream$StreamDecoder.skipField(CodedInputStream.java:2100)
> 	at com.google.protobuf.GeneratedMessageV3.parseUnknownFieldProto3(GeneratedMessageV3.java:303)
> 	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse.<init>(WorkerProtocol.java:1866)
> 	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse.<init>(WorkerProtocol.java:1830)
> 	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse$1.parsePartialFrom(WorkerProtocol.java:2420)
> 	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse$1.parsePartialFrom(WorkerProtocol.java:2415)
> 	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
> 	at com.google.protobuf.AbstractParser.parsePartialDelimitedFrom(AbstractParser.java:262)
> 	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:275)
> 	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:280)
> 	at com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:49)
> 	at com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(GeneratedMessageV3.java:347)
> 	at com.google.devtools.build.lib.worker.WorkerProtocol$WorkResponse.parseDelimitedFrom(WorkerProtocol.java:2082)
> 	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:313)
> 	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:154)
> 	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:112)
> 	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:95)
> 	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:63)
> 	at com.google.devtools.build.lib.exec.SpawnActionContextMaps$ProxySpawnActionContext.exec(SpawnActionContextMaps.java:362)
> 	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:287)
> 	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:294)
> 	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:960)
> 	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:891)
> 	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:115)
> 	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:746)
> 	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:700)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:442)
> 	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:503)
> 	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:224)
> 	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:382)
> 	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ---8<---8<--- End of exception details ---8<---8<---
> 
> ---8<---8<--- Start of log ---8<---8<---
> -Xbootclasspath/p is no longer a supported option.
> ion.
> ---8<---8<--- End of log ---8<---8<---
> Target //src:bazel failed to build
> INFO: Elapsed time: 175.594s, Critical Path: 43.26s
> INFO: 1234 processes: 1234 local.
> FAILED: Build did NOT complete successfully
> 
> ERROR: Could not build Bazel

**Comment by psyhtest** [comment]
Hi @ztyree42, Could you please first try to install JDK 1.8.0.131:
```
$ ck install package --tags=java,v8u131
```
then Bazel v0.15.2 using the above version of JDK:
```
$ ck install package --tags=tool,bazel,v0.15 --dep_add_tags.java-compiler=java,v8u131
```
and then finally TensorFlow.
